### ISSUE TITLE
Links to codeplex don't work for branches with last commits on GitHub

### ISSUE THREAD

**Issue by dpen2000** [ashmind/TryRoslyn#11]
I've fixed links to commits in #10. Links to authors still don't work (I couldn't see how to get the files in App_Data to get website to run): might be easiest to remove these links to authors

**Comment by ashmind** [comment]
Thanks, I'll take a look. Btw Build-Roslyn-Local should give you the required files.

**Comment by ashmind** [comment]
Yep, I have removed link to author (not really needed).
