### ISSUE TITLE
abspos change in flex spec breaks header

### ISSUE THREAD

**Issue by gregwhitworth** [ashmind/TryRoslyn#13]
Hey @ashmind,

The header breaks due to the update in the [flex spec](http://dev.w3.org/csswg/css-flexbox/#abspos-items). This can currently be seen in Project Spartan and Mozilla and Google are currently updating their behavior to match. On twitter you requested screensize, this is on 1920 x 1080. Let me know if you have any questions. Thanks!!
![abspos-flex](https://cloud.githubusercontent.com/assets/865244/7193670/ef46ac22-e458-11e4-9a67-ae46b8df61b9.PNG)

**Comment by ashmind** [comment]
Thanks for the spec link! I'll try to take a look later today (NZ evening).

**Comment by ashmind** [comment]
Not sure how I can test this though -- both Chrome and Firefox stable render it without visual issues. And I don't see a way to install "Spartan" on Windows 9 to test.

I'll wait until either Spartan is released or it breaks in Chrome/Firefox.

**Comment by ashmind** [comment]
OK I can test it in Edge now, I'll try to get a fix done soon-ish.

**Comment by gregwhitworth** [comment]
Awesome, I just pushed a bit on the Chrome/Firefox team and they both bumped the priorities. So expect Chrome/FF to break sooner rather than later.
