### ISSUE TITLE
Crash on a specific source

### ISSUE THREAD

**Issue by ashmind** [ashmind/TryRoslyn#15]
@SLaks:
> @ashmind TryRoslyn chokes on http://tryroslyn.azurewebsites.net/#b:master/f:sr/K4Zwlgdg5gBAygTxAFwKYFsDcAoUlaIoYB0AMpAI7ECiAHgA4BOqI4A9hCDtnUy+xAA8AMWAQAxoMjIANDGkA+BTFowAvCvXLVG2piAA

**Comment by SLaks** [comment]
This is a Roslyn compiler bug!
https://github.com/dotnet/roslyn/issues/3826

**Comment by ashmind** [comment]
@SLaks seems to be fixed now, thanks!
