### ISSUE TITLE
Allow change the language version to expirimental

### ISSUE THREAD

**Issue by AviAvni** [ashmind/TryRoslyn#18]
to use other branch like roslyn/local-functions

**Comment by ashmind** [comment]
@AviAvni Is it broken right now? I was sure I always set the language to max available version.

**Comment by AviAvni** [comment]
still broken 
![image](https://cloud.githubusercontent.com/assets/1097246/9035645/8b6d441a-39e2-11e5-9c11-be8041dc7fd9.png)

**Comment by ashmind** [comment]
It seems that I must specifically allow each experimental feature by name, e.g.
> options.WithFeature("localFunctions", "true")

To do that, I need to know the names of features available in each branch.
I'll do some research, but this is unlikely to be fixed this week.

**Comment by AviAvni** [comment]
maybe it's can be added in the website(with textbox) not autoatically at first

**Comment by ashmind** [comment]
@AviAvni I have updated the code to autodiscover experimental features. I have problems building roslyn/local-functions specifically, but here's an example in another branch:
http://tryroslyn.azurewebsites.net/#b:demos-compiler/K4Zwlgdg5gBAygTxAFwKYFsDcAoADsAIwBswBjGUogQxBBgGEYBvbGNmfYsmANwHswAExgBZABQBKZq3az+QmAEFJzGAF9Z7GZqWScstdjVA

**Comment by AviAvni** [comment]
@ashmind great thanks
