### ISSUE TITLE
Please add new C#7 features support

### ISSUE THREAD

**Issue by OlegJakushkin** [ashmind/TryRoslyn#21]
Roslyn updated with support for code like this:

```
using System;
public class C {
    public ref int M() {
        int [] numbers = { 0b1, 0b0___01 };
        return ref numbers;
    }
}
```
(released in April)

Please add its support to TryRoslyn.

**Comment by ashmind** [comment]
@OlegJakushkin I've added the support -- still have problems compiling some branches, but here is the one where most of it works:
http://tryroslyn.azurewebsites.net/#b:demos-compiler/K4Zwlgdg5gBAygTxAFwKYFsDcAoADsAIwBswBjGUogQxBBgGEYBvbGNmfYsmAJ1QDMYkZDACyACgCUzVuznCYAbQC6MCMHQFUPOgF5mMAAwEAjABojBQwH1bhkzAC+OOXL7JgPCLwFqNWnRd2R2xHIA=
