### ISSUE TITLE
Release mode has no effect

### ISSUE THREAD

**Issue by pentp** [ashmind/TryRoslyn#28]
See for example [this](http://tryroslyn.azurewebsites.net/#b:master/f:%3Eil/K4Zwlgdg5gBAygTxAFwKYFsDcAoADsAIwBswBjGUogQxBBgGEYBvbGNmfYsmANwHswAExgBZABSRkAfhgAzPnwCUzVu3aq1bMLJhj5fGGDqTeVIsFSKNmlprsxr9gOL0AdAGlUqXAEESPVDEeMwtXABU+OGQAJ0goMUVFHHsYAF9HdlQiEFQMtlsU9hcPL19/QIhgIiIkvLTrdNSgA==). Lots of NOP instructions in the generated IL and there is no difference when choosing Debug or Release.

**Comment by ashmind** [comment]
@pentp Good catch, I'll try to take a look later today.
