### ISSUE TITLE
Exception message should preserve newlines

### ISSUE THREAD

**Issue by svick** [ashmind/TryRoslyn#29]
When Roslyn throws an exception while compiling some code (for example: https://github.com/dotnet/roslyn/issues/13365), the stack trace of the exception is shown with all its lines mushed together as if it was one line:

![](http://imgur.com/vC5wu6p.png)

It would be better if the newlines in the stack trace were preserved, for example by using the `whitespace: pre` style:

![](http://imgur.com/7RSB4yW.png)

**Comment by ashmind** [comment]
@svick Thanks!
