### ISSUE TITLE
Move to https

### ISSUE THREAD

**Issue by ashmind** [ashmind/TryRoslyn#31]

**Comment by xanatos** [comment]
There is a problem with Chrome: the https site is pointing to the ws service, so the chrome stops it: 

> Mixed Content: The page at 'https://tryroslyn.azurewebsites.net/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://tryroslyn.azurewebsites.net/mirrorsharp'. This request has been blocked; this endpoint must be available over WSS.

**Comment by ashmind** [comment]
@xanatos Thanks -- I can fix it separately, but I'll probably fix it together with this ticket.

**Comment by xanatos** [comment]
Now it works! Thanks a lot! (I have a problem with the proxy of my workplace where ws:// connections don't work but wss:// work :-) )
