### ISSUE TITLE
Add LICENSE.md/txt

### ISSUE THREAD

**Issue by davidfowl** [ashmind/TryRoslyn#38]
What license is this code?

**Comment by ashmind** [comment]
@davidfowl I'll add some reasonable one later today — would MIT or BSD work for you?
And I would appreciate discussion if you want to fork it or reuse a significant part, because I have some huge changes planned (https://github.com/ashmind/mirrorsharp)

**Comment by ashmind** [comment]
@davidfowl Added 2-clause BSD, please let me know if you have any issues with it.
