### ISSUE TITLE
Allow viewing IL differences between compilers

### ISSUE THREAD

**Issue by OmerRaviv** [ashmind/TryRoslyn#5]
It would be really interesting to be able to use TryRoslyn to learn about differences in the output IL between Roslyn and the C# 5.0 compiler. This would require allowing the user to choose "IL" on the right-hand instead of Decompiled C#, and allowing the user to choose pre-Roslyn versions of the compiler on the left-hand-side.

**Comment by ashmind** [comment]
Closing to cleanup the queue.
