### ISSUE TITLE
Some branches fail after build (e.g. https://tr-b-ashmind-features-coalesce-assignment.azurewebsites.net/status) 

### ISSUE THREAD

**Issue by ashmind** [ashmind/TryRoslyn#61]

**Comment by svick** [comment]
Is this the reason why the dropdown currently does not contain the `master` branch?

**Comment by ashmind** [comment]
@svick Thanks for reporting -- that seems to be a separate issue where master failed to build (my bug), and built excluded it. I created a ticket to make sure such branches don't just disappear (gh-69).

I've also just forced a rebuild, should appear soon.

**Comment by ashmind** [comment]
@svick master branch is available now.

**Comment by svick** [comment]
@ashmind Thanks.

**Comment by ashmind** [comment]
Since old branches will fail the new build anyway, I'll close this until I see it again.
