### ISSUE TITLE
Site does not work in Internet Explorer

### ISSUE THREAD

**Issue by svick** [ashmind/TryRoslyn#68]
When I open the site in Internet Explorer 11, it's completely broken:

![tryroslyn](https://cloud.githubusercontent.com/assets/287848/23754929/08fe7fca-04df-11e7-9827-5e1965310596.PNG)

F12 console shows the following error, which could be related:

> SCRIPT1004: Expected ';'
> app.min.js (56,6)

I found this out when trying to reproduce https://github.com/ashmind/TryRoslyn/issues/67 in other browsers. I don't know if any developer actually uses IE, so this issue might not be worth fixing.

**Comment by ashmind** [comment]
@svick Thanks -- this is by design, I decided to draw a line at certain JS features and IE doesn't support those. Obviously a better error message would be good, I'll create a ticket for that.
