### ISSUE TITLE
Update Release (NuGet) to Roslyn 2.0

### ISSUE THREAD

**Issue by svick** [ashmind/TryRoslyn#73]
NuGet packages for Roslyn 2.0.0 (with support for C# 7.0) have been released, but as far as I can tell, TryRoslyn is still using Roslyn 1.x for the "Release (NuGet)" option. I think it should be updated to 2.0.0.

**Comment by ashmind** [comment]
@svick Yep, I agree this makes sense.
My main question about this was whether all current branches of roslyn are compatible with 2.0, but I think the interesting ones should be.

I'll take a look later today (NZ time).

**Comment by ashmind** [comment]
Related to ashmind/mirrorsharp#63.

**Comment by svick** [comment]
Thank you, it seems to work now.
