### ISSUE TITLE
Add symbolic names to addresses in JIT asm

### ISSUE THREAD

**Issue by ashmind** [ashmind/TryRoslyn#81]

**Comment by ashmind** [comment]
See also: https://github.com/ashmind/TryRoslyn/issues/39#issuecomment-298203705.

**Comment by ashmind** [comment]
@noahfalk, @davidfowl
Added symbolic addresses (where possible).

Ideas on how to resolve the call here https://tryroslyn.azurewebsites.net/#f:>asmr/M4FwhiCWDGAE0BszGLAwrA3gWAFCwNlAhlkgDsRYBZACgpAG0BdWADwEotY9C/YATgFMQAVwHl2jAKzMA3L0IBfPEqA= ? Something internal/array-related?

**Comment by noahfalk** [comment]
Well that was fast... I thought it would cause you more grief. Nice work!

That call is presumably a JIT helper that is going to throw the IndexOutOfBoundsException. I don't recall whether we dynamically generate it or its compiled as part of clr.dll, but in either case I don't think there is a good way for you to get a symbol for it. If you were using coreclr.dll compiled yourself then you'd have access to your own private symbols and you might be able to resolve it using DIA.

**Comment by mattwarren** [comment]
As an extension to this you *may* be able to use the `IDebugClient` interface of `DataTarget` to get WinDBG to help you out (the SOS '-u' cmd), see https://github.com/Microsoft/clrmd/issues/34 for more info. 

But it requires downloading symbols from a 'symbol server', so I'm not sure if you want to go down that route.

**Comment by mattwarren** [comment]
Also you might find some useful code in the excellent [msos](https://github.com/goldshtn/msos) tool by @goldshtn, see [Disassemble.cs](https://github.com/goldshtn/msos/blob/master/msos/Disassemble.cs) for starters

**Comment by ashmind** [comment]
@mattwarren Thanks! I'll track it separately under #89.
